### ISSUE TITLE
1D barcode not showing on apple watch

### ISSUE THREAD

**Issue by ape47** [Creapptor/passdock#12]
1D barcode (code128) not showing on apple watch.

got a blank pass

WatchOS 3.2

**Comment by TsukiakariUsagi** [comment]
I’m on WatchOS 4.0 with a Series 3 Watch and it doesn’t work either.  I just created a pass last night for a new fitness centre card and it (finally) worked properly inside of Wallet on my iPhone 6S+, but it doesn’t have the same behaviour on the Watch like my other membership cards, like Starbucks or AMC Theatres.

**Comment by TsukiakariUsagi** [comment]
I did a little further digging myself through Apple’s Wallet Dev Guide (https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html - about halfway down the Guide under “Barcodes Link Passes to Your Records”, the last half of the second paragraph) and found the following:

watchOS does not support the PKBarcodeFormatCode128 format. If a PKBarcodeFormatCode128 barcode is included in the barcodes array, an alternative barcode is used as fallback; if a PKBarcodeFormatCode128 barcode is the only barcode you supply, no barcode is displayed.

Please disregard my additional comment and close the issue since it isn’t a Passdock issue but an Apple issue.
